### ISSUE TITLE
How to add GestureRecongnizer to whole page?

### ISSUE THREAD

**Issue by ngrj** [glepur/react-native-swipe-gestures#11]
Hi sorry I looked through whole Read me but I wasn't able to determine how to do it, I've a modal which I show on clicking button(using react-native-navigation by wix), it was all working well but when I added GestureRecongnizer to it, the modal won't pop up. I get the following log in my console: 

> React: Got DOWN touch before receiving UP or CANCEL from last gesture

Following is my code:
`  renderLoadingView() {
    return (
      <GestureRecognizer onSwipeDown={() => closeModal()} config={SWIPE_CONFIG}>
        <View style={styles.loading} >
          <Text>
              {this.state.loadingText}
          </Text>
        </View>
      </GestureRecognizer>
    );
  }
`

I need to add detect swipe down action on whole page if there is a better place please let me know.

**Comment by glepur** [comment]
Proper way to add swipe detection to whole page is to cover whole page with `GestureRecognizer`.
Log message you provided is not created by this module, it is created by React Native.
It is possible that some of the other modules are interfering with `GestureRecognizer`, so try checking that, and if you don't figure it out post a question on [SO](https://stackoverflow.com/).
Good luck!
