### ISSUE TITLE
Swipe Gesture component breaks ScrollView

### ISSUE THREAD

**Issue by TylerB24890** [glepur/react-native-swipe-gestures#15]
I have a ScrollView wrapped in a `<GestureRecognizer>` component. The Swipe action works great, but the scroll view stopped scrolling properly. It's very glitchy and hardly detects scroll events.

**Comment by TylerB24890** [comment]
I fixed this issue by returning a `<ScrollView>` component as the `<GestureRecognizer>` instead of the standard `<View>` -- all seems to be working as expected.

**Comment by ptquang86** [comment]
@TylerB24890 can you please give me an example?

**Comment by timhorwood** [comment]
I also have this issue, have you got an example? Thanks

**Comment by TylerB24890** [comment]
The needs for this functionality has since changed, however I was needing to use a `SectionList` component and have the `GestureRecognizer` detect a left swipe. Where the default `<GestureRecognizer>` component returns a standard `<View>`, I just changed it to `return (<SectionList {...this.props} {...this._panResponder.panHandlers}/>);`

**Comment by Kosiarznerek** [comment]
I found another way around. Had a similar problem, but it couldn't have been fixed with your solution, because beside ScrollView I had some other components. I just adjust gestureRecognizer to my purposes in that way that it is only able to detect left and right swipe. You can see code [here.](https://github.com/Kosiarznerek/react-native-typescript-recipes/blob/master/compotents/SwipeRecognizer.tsx)

**Comment by dooleyb1** [comment]
Having the same issue, anyone get a solution without editing the library source code itself?

**Comment by pluvd7j** [comment]
Try this way, It's working for me
`
import GestureRecognizer, {
  swipeDirections,
} from "react-native-swipe-gestures";

const nextData = () => {
   
     swipeRightAnimation.start(() => {
      //Your code here
    });
  };
  
  const prevData = () => {
   
     swipeLeftAnimation.start(() => {
      //Your code here
    });
  };

 const config = {
    velocityThreshold: 0.3,
    directionalOffsetThreshold: 80,
  };

  const translateX = new Animated.Value(0);
  const handlePan = Animated.event(
    [{ nativeEvent: { translationY: translateX } }],
    { useNativeDriver: true }
  );
  const reset = Animated.timing(translateX, {
    toValue: 0,
    duration: 250,
    useNativeDriver: true,
  });

  const swipeLeftAnimation = Animated.timing(translateX, {
    toValue: 600,
    duration: 400,
    useNativeDriver: true,
  });

  const swipeRightAnimation = Animated.timing(translateX, {
    toValue: -600,
    duration: 400,
    useNativeDriver: true,
  });

  const onSwipe = (gestureName, gestureState) => {
    const { SWIPE_LEFT, SWIPE_RIGHT } = swipeDirections;

    switch (gestureName) {
      case SWIPE_LEFT:
        handlePan;
        break;
      case SWIPE_RIGHT:
        handlePan;
        break;
    }
  }; 

return (
<SafeAreaView style={styles.container} edges={["left", "right", "bottom"]}>
      <GestureRecognizer
        onSwipe={(direction, state) => onSwipe(direction, state)}
        onSwipeUp={(state) => reset.start()}
        onSwipeDown={(state) => reset.start()}
        onSwipeLeft={(state) => nextData(state)}
        onSwipeRight={(state) => PrevData(state)}
        config={config}
        style={{
          flex: 1,
        }}
      >
        <Animated.View
          style={{ width: "100%", height: "100%", transform: [{ translateX }] }}
        >
          <ScrollView
            style={{
    height: "90%",
    width: "100%",
    alignSelf: "center",
  }}
   showsVerticalScrollIndicator={false}
          >
       <Text>Here your code</Text>
          </ScrollView>
        </Animated.View>
      </GestureRecognizer>
    </SafeAreaView>)`
