### ISSUE TITLE
works on iOS, but not Android

### ISSUE THREAD

**Issue by AndresTIY** [glepur/react-native-swipe-gestures#18]
The swipe gestures work perfectly on iOS, yet on Android, it doesn't work. The action will fire randomly when swiping.. maybe once every 10-20 swipe attempts? 

Any suggestions or solutions?

Thank you.

**Comment by AndresTIY** [comment]
I didn't wrap the entire `<View>` with the Gesture component. The outer `<View>` had a flex of 1, so the Gesture only worked on the components within but not the entire screen. This is why it seemed like it worked randomly, because it only worked on the limited space of the text. 

I then wrapped everything and now it works! Don't understand why it worked on iOS though compared to Android.

**Comment by marconett** [comment]
for the record: i encountered the same problem and fixed it by setting the android specific `elevation` prop onto the `GestureRecognizer`

**Comment by garmoshka-mo** [comment]
Same issue for me, but wasn't able to resolve for react-native-swipe-gestures

I've found simpler solution, that to use this lib - works perfect:

```
<View
      onTouchStart={e=> this.touchY = e.nativeEvent.pageY}
      onTouchEnd={e => {
        if (this.touchY - e.nativeEvent.pageY > 20)
          console.log('Swiped up')
      }}
      style={{height: 300, backgroundColor: '#ccc'}}
    >
```
