### ISSUE TITLE
Swipe does not work  on Android 

### ISSUE THREAD

**Issue by aatish-rajkarnikar** [glepur/react-native-swipe-gestures#21]
i was trying to implemented this lib to my project and it works perfectly fine on iOS but doesn't work on Android. Is this lib is for iOS only??

**Comment by aatish-rajkarnikar** [comment]
found out playing with config fixed the issue. thanks!

**Comment by vishaljadav24** [comment]
@aatish-rajkarnikar  Can you tell which config works for you?

**Comment by dhamodar** [comment]
@aatish-rajkarnikar  Can you tell me which config works for you?
