### ISSUE TITLE
Swipe in modal issue

### ISSUE THREAD

**Issue by rollsroyc3** [glepur/react-native-swipe-gestures#27]
Ive implemented swipe-gestures in parts of my app, but had issues in a modal. I found this [issue](https://github.com/glepur/react-native-swipe-gestures/issues/8) and it seems like there is no real concrete solution. But then I realized I am also using [React-Native-Snap-Carousel](https://github.com/archriss/react-native-snap-carousel) and swipe works just fine in the modal. Any idea what the difference is?

**Comment by rollsroyc3** [comment]
Nevermind, looks like there just using a scrollview or flatlist.

**Comment by alainib** [comment]
calling this component inside modal don't work for me too. 
any update since ? 
thank you

**Comment by emiltsang** [comment]
try to wrap the modal inside gesture handler
<GestureRecognizer>
<Modal />
</GestureRecognizer>
