### ISSUE TITLE
block your child's events

### ISSUE THREAD

**Issue by sphairo** [glepur/react-native-swipe-gestures#3]
<GestureRecognizer
                velocityThreshold={0.1}
                onSwipeDown={(state) => this.onSwipeDown(state)}
                style={style}>
                <Text>{this.state.myText}</Text>
                <Text>onSwipe callback received gesture: {this.state.gestureName}</Text>
                {MyCustomView}
                {MyHorizontalScroll}
            </GestureRecognizer>

Now i can not listening when i scrolling my scrollview :(

**Comment by glepur** [comment]
It is impossible to allow scroll within child components. That would block swipe on all content inside `GestureRecognizer`. Put your `ScrollView` outside of `GestureRecognizer`.
