### ISSUE TITLE
ListViews don't scroll inside of GestureRecognizer on iOS

### ISSUE THREAD

**Issue by groke** [glepur/react-native-swipe-gestures#5]
The same code works fine on android, but when I put a scrollview inside of the GestureRecognizer the scrolling is interrupted and it only moves a fraction of an inch.

```
  <GestureRecognizer
          onSwipeLeft={(state) => this.onSwipeLeft(state)}
          onSwipeRight={(state) => this.onSwipeRight(state)}
  >
     <ListView
             dataSource={this.dataSource}
             renderRow={this.renderRow.bind(this)}
            />
  </GestureRecognizer>
```

**Comment by glepur** [comment]
This happens because touch event propagates to `GestureRecognizer`. You should put `ListView` outside of `GestureRecognizer`.
`GestureRecognizer` is build on top of RN `PanResponder`, and this is known bug https://github.com/facebook/react-native/issues/11206.

**Comment by jcollum** [comment]
Is there a way to pass the event to the Scrollview or ignore it? Like if I want to swipe right/left but scroll up/down, I'd only want to respond to right/left gestures.

**Comment by samridhgupta** [comment]
@jcollum looking for a similar approach to the above issue, is there any update on this issue?

**Comment by jcollum** [comment]
Sorry, no update. I think I decided to change the way my app behaves -- I was using swiping for navigation; decided that wasn't good because it means you have to touch 3 times to go to a specific screen instead of just touching an icon.
