### ISSUE TITLE
Pass through of up/down motion while capturing left/right?

### ISSUE THREAD

**Issue by dereksweet** [glepur/react-native-swipe-gestures#7]
Great component, thank you so much. Works great. I am wondering, is there any way to pass through the up/down gestures while capturing the left/right gestures with your component? I ask because I would like a ListView on the screen that can still be naturally scrolled up and down but capture a left/right swipe to change sections..

**Comment by glepur** [comment]
Hi. I'm glad that you like the component.
Currently, this component does not support that. Issue is with RN `PanResponder` interacting badly with other touch sensitive components. Facebook is aware of this, and I think it will be solved before it hits release.

**Comment by chrismcleod** [comment]
@dereksweet 

I was able to extract a separate component from this source that can do what you want.  Basically the idea is to only become the responder for swipes in the directions you are interested in.  Here is a the source for a vertical swipes only component.  This is the same code as glepur's I have just removed all horizontal related code and added a conditional to the logic for becoming the responder:

```typescript
import * as React from 'react'

import { GestureResponderEvent, PanResponder, PanResponderGestureState, PanResponderInstance, View } from 'react-native'

export const swipeDirections = {
  SWIPE_UP: 'SWIPE_UP',
  SWIPE_DOWN: 'SWIPE_DOWN'
}

const swipeConfig = {
  velocityThreshold: 0.3,
  directionalOffsetThreshold: 80
}

const isValidSwipe = (velocity: number, velocityThreshold: number, directionalOffset: number, directionalOffsetThreshold: number) => {
  return Math.abs(velocity) > velocityThreshold && Math.abs(directionalOffset) < directionalOffsetThreshold
}

export class VerticalPanHandler extends React.Component<any, any> {

  private swipeConfig: any
  private _panResponder: PanResponderInstance

  constructor(props: any) {
    super(props)
    this.swipeConfig = Object.assign(swipeConfig, props.config)
  }

  componentWillReceiveProps(props: any) {
    this.swipeConfig = Object.assign(swipeConfig, props.config)
  }

  componentWillMount() {
    const responderEnd = this._handlePanResponderEnd.bind(this)
    const shouldSetResponder = this._handleShouldSetPanResponder.bind(this)
    this._panResponder = PanResponder.create({ // stop JS beautify collapse
      onStartShouldSetPanResponder: shouldSetResponder,
      onMoveShouldSetPanResponder: shouldSetResponder,
      onPanResponderRelease: responderEnd,
      onPanResponderTerminate: responderEnd
    })
  }

  _handleShouldSetPanResponder(evt: GestureResponderEvent, gestureState: PanResponderGestureState) {
    return evt.nativeEvent.touches.length === 1
      && !this._gestureIsClick(gestureState)
      && (
        this._getSwipeDirection(gestureState) === swipeDirections.SWIPE_UP
        ||
        this._getSwipeDirection(gestureState) === swipeDirections.SWIPE_DOWN
      )
  }

  _gestureIsClick(gestureState: PanResponderGestureState) {
    return Math.abs(gestureState.dx) < 5 && Math.abs(gestureState.dy) < 5
  }

  _handlePanResponderEnd(_evt: GestureResponderEvent, gestureState: PanResponderGestureState) {
    const swipeDirection = this._getSwipeDirection(gestureState)
    this._triggerSwipeHandlers(swipeDirection, gestureState)
  }

  _triggerSwipeHandlers(swipeDirection: string | null, gestureState: PanResponderGestureState) {
    const { onSwipe, onSwipeUp, onSwipeDown } = this.props
    const { SWIPE_UP, SWIPE_DOWN } = swipeDirections
    if (onSwipe) onSwipe(swipeDirection, gestureState)
    switch (swipeDirection) {
      case SWIPE_UP:
        if (onSwipeUp) onSwipeUp(gestureState)
        break
      case SWIPE_DOWN:
        if (onSwipeDown) onSwipeDown(gestureState)
        break
      default: break
    }
  }

  _getSwipeDirection(gestureState: PanResponderGestureState) {
    const { SWIPE_UP, SWIPE_DOWN } = swipeDirections
    const { dy } = gestureState
    if (this._isValidVerticalSwipe(gestureState)) {
      return (dy > 0)
        ? SWIPE_DOWN
        : SWIPE_UP
    }
    return null
  }

  _isValidVerticalSwipe(gestureState: PanResponderGestureState) {
    const { vy, dx } = gestureState
    const { velocityThreshold, directionalOffsetThreshold } = this.swipeConfig
    return isValidSwipe(vy, velocityThreshold, dx, directionalOffsetThreshold)
  }

  render() {
    return (<View {...this.props} {...this._panResponder.panHandlers} />)
  }
}
```

**Comment by leuducquy** [comment]
And this is only for swiper left and right .
`import * as React from 'react'

import { GestureResponderEvent, PanResponder, PanResponderGestureState, PanResponderInstance, View } from 'react-native'

export const swipeDirections = {
  SWIPE_UP: 'SWIPE_LEFT',
  SWIPE_DOWN: 'SWIPE_RIGHT'
}

const swipeConfig = {
  velocityThreshold: 0.3,
  directionalOffsetThreshold: 80
}

const isValidSwipe = (velocity: number, velocityThreshold: number, directionalOffset: number, directionalOffsetThreshold: number) => {
  return Math.abs(velocity) > velocityThreshold && Math.abs(directionalOffset) < directionalOffsetThreshold
}

export class HorizontalPanHandler extends React.Component<any, any> {

  private swipeConfig: any
  private _panResponder: PanResponderInstance

  constructor(props: any) {
    super(props)
    this.swipeConfig = Object.assign(swipeConfig, props.config)
  }

  componentWillReceiveProps(props: any) {
    this.swipeConfig = Object.assign(swipeConfig, props.config)
  }

  componentWillMount() {
    const responderEnd = this._handlePanResponderEnd.bind(this)
    const shouldSetResponder = this._handleShouldSetPanResponder.bind(this)
    this._panResponder = PanResponder.create({ // stop JS beautify collapse
      onStartShouldSetPanResponder: shouldSetResponder,
      onMoveShouldSetPanResponder: shouldSetResponder,
      onPanResponderRelease: responderEnd,
      onPanResponderTerminate: responderEnd
    })
  }

  _handleShouldSetPanResponder(evt: GestureResponderEvent, gestureState: PanResponderGestureState) {
    return evt.nativeEvent.touches.length === 1
      && !this._gestureIsClick(gestureState)
      && (
        this._getSwipeDirection(gestureState) === swipeDirections.SWIPE_LEFT
        ||
        this._getSwipeDirection(gestureState) === swipeDirections.SWIPE_RIGHT
      )
  }

  _gestureIsClick(gestureState: PanResponderGestureState) {
    return Math.abs(gestureState.dx) < 5 && Math.abs(gestureState.dy) < 5
  }

  _handlePanResponderEnd(_evt: GestureResponderEvent, gestureState: PanResponderGestureState) {
    const swipeDirection = this._getSwipeDirection(gestureState)
    this._triggerSwipeHandlers(swipeDirection, gestureState)
  }

  _triggerSwipeHandlers(swipeDirection: string | null, gestureState: PanResponderGestureState) {
    const { onSwipe, onSwipeUp, onSwipeDown } = this.props
    const { SWIPE_LEFT, SWIPE_RIGHT } = swipeDirections
    if (onSwipe) onSwipe(swipeDirection, gestureState)
    switch (swipeDirection) {
      case SWIPE_LEFT:
        if (onSwipeLeft) onSwipeLeft(gestureState)
        break
      case SWIPE_RIGHT:
        if (onSwipeRight) onSwipeRight(gestureState)
        break
      default: break
    }
  }

  _getSwipeDirection(gestureState: PanResponderGestureState) {
    const { SWIPE_LEFT, SWIPE_RIGHT } = swipeDirections
    const { dx } = gestureState
    if (this._isValidHorizontalSwipe(gestureState)) {
      return (dx > 0)
        ? SWIPE_RIGHT
        : SWIPE_LEFT
    }
    return null
  }

  _isValidHorizontalSwipe(gestureState: PanResponderGestureState) {
    const { vy, dx } = gestureState
    const { velocityThreshold, directionalOffsetThreshold } = this.swipeConfig
    return isValidSwipe(vx, velocityThreshold, dy, directionalOffsetThreshold)
  }

  render() {
    return (<View {...this.props} {...this._panResponder.panHandlers} />)
  }
}`

**Comment by franciscailleAstus** [comment]
Has this been fixed ? 
It seems to work most of the time, but not always. Sometimes, when I scroll Up/Down, it stop scrolling before the end/start of the page. Even tho I used the same amount of force/velocity in my movement. I also watch only left/right movements with this component.

Thanks in advance for the help !
