### ISSUE TITLE
Provide the original synthetic event to gesture event handlers

### ISSUE THREAD

**Issue by nicosommi** [glepur/react-native-swipe-gestures#9]
I'm working in a user case in which I need to stopPropagate the event in the swipe right event handler, but it's not in the payload received (which is just gestureState).

Since this is a high level event, I don't know if it's correct to just use the event that the Pan Responder sends, but it may be useful at the very least to have something like a "getOriginalEvent" method on the new Synthetic Event created for this new event, or some solution like that.
Let's discuss it.

I can workaround it with a internal state, but it will be cool to have access to the synthetic event object.

Let me know if you're interested I can create a PR.

**Comment by glepur** [comment]
I am not sure if your idea will work. In RN touch propagates from outside to inner elements until one of them captures and becomes responder. Even if you access `evt.nativeEvent` I don't think `stopPropagation` would do anything. Let me know if I'm wrong.

Regarding the `react-native-swipe-gestures` API. Passing `SyntheticEvent` as additional parameter is not breaking change but I'm trying to keep it as simple as possible. 
For more complex features I think people will fall back to `PanResponder` directly?

**Comment by nicosommi** [comment]
@glepur Thanks. I was reading and trying things out. You're right, the default capture/bubbling mechanism does apply for regular events and stop propagation works, but that does not apply to this higher level set of gesture responder events because is managed by it's grant/reject mechanism.
So the issue does not make much sense. Closing it.
